### ISSUE TITLE
Form Feedback: Can't upload file when using form in Fenix, nor select issue type

### ISSUE THREAD

**Issue by bbinto** [mozilla/oi-fenix-campaign#9] opened 2019-04-08 17:58 UTC
When clicking the browse button, nothing happens, same goes for dropdown box for issue type

**Comment by MichaelKohler** [comment] 2019-04-08 18:18
Interesting, just tested this with the latest Fenix version from the Play Store on a Nokia 5, Android 9.

1) When I click browse, it opens the Android chooser and I can choose a picture. However, that picture won't finally be uploaded to the GitHub issue, will look into that.. But "nothing happens" should definitely not be happening. What version are you using?

![photo5287403379498265225](https://user-images.githubusercontent.com/330324/55746885-70da6d00-5a2a-11e9-8d3e-04477ccc384c.jpg)

2) Same goes for the dropdown for issue type, this works for me:

![photo5287403379498265226](https://user-images.githubusercontent.com/330324/55746951-9c5d5780-5a2a-11e9-850e-0e0dcfacf55c.jpg)

**Comment by MichaelKohler** [comment] 2019-04-08 18:28
Oh wait, I see. Sorry. For me the image chooser comes up, but then the field still says "No file selected" and therefore won't be uploaded. I fear this is a Fenix bug. I will create a smaller testcase and file a Fenix bug if indeed it's a fenix bug!

**Comment by bbinto** [comment] 2019-04-08 18:33
For me, it doesn't even let me select the issue type dropdown box.

Here is my Fenix version:  ![Screenshot_20190408-072110](https://user-images.githubusercontent.com/122897/55747852-3b725700-5a0b-11e9-86bd-cd9a2f3b1112.png)

As for the choose file, also here, it doesn't literally do anything once I tap it.

**Comment by MichaelKohler** [comment] 2019-04-08 19:03
I'll see if I can get hold of that specific version and reproduce it. Seems like a Fenix bug to me though :/

For the issue I saw regarding "No file selected", I've filed https://github.com/mozilla-mobile/fenix/issues/1467

**Comment by couci** [comment] 2019-05-15 15:17
@MichaelKohler let's take the upload screenshot off for now until the bug is fixed

**Comment by MichaelKohler** [comment] 2019-05-15 15:18
when do you want to launch? The bug will be fixed quite soon (PR is here: https://github.com/mozilla-mobile/fenix/pull/2513)

**Comment by MichaelKohler** [comment] 2019-05-15 16:51
It's out, once the fixed version is on Play Store I'll add it again.

**Comment by MichaelKohler** [comment] 2021-03-03 18:30
Closing this as I'm archiving the repo.

**Closed as completed by MichaelKohler** 2021-03-03 18:30 UTC
Labels: question
